aa = ao;
print(aa);

-- local aa = a();
-- r(aa + aa + aa / aa + aoa + aooa + 101)
-- r(aa + aa + aa / aa + aoa + aooa + 101)
-- r(aa + aa + aa / aa + aoa + aooa + 101)
-- r(aa + aa + aa / aa + aoa + aooa + 101)
-- r(aa + aa + aa / aa + aoa + aooa + 101)
-- r(aa + aa + aa / aa + aoa + aooa + 101)
-- local aa = a();
-- local aa = a();
-- local aa = a();
-- local aa = a();
-- local aa = a();
-- local aa = a();
-- local aa = a();
-- local aa = a();
-- if (aa and aa and aa) then
--     humpday();
--     aa = 10;
--     if (aa and aa or aa) then
--         humpday();
--         aa = 10;
--     end
--     if (aa and aa and aa) then
--         humpday();
--         aa = 10;
--     end
--     if (aa and aa or aa) then
--         humpday();
--         aa = 10;
--     end
-- end
-- 
-- aa += 10;
-- aa -= aa;
-- 
-- local a = ((((all == all) == all) == (all == all) == all) == (((all == all) == all) == (all == all) == all)) == (((all == all) == all) == (all == all) == all) == (((all == all) == all) == (all == all) == all) ==  ((((all == all) == all) == (all == all) == all) == (((all == all) == all) == (all == all) == all)) == (((all == all) == all) == (all == all) == all) == (((all == all) == all) == (all == all) == all) ==  ((((all == all) == all) == (all == all) == all) == (((all == all) == all) == (all == all) == all)) == (((all == all) == all) == (all == all) == all) == (((all == all) == all) == (all == all) == all) ==  ((((all == all) == all) == (all == all) == all) == (((all == all) == all) == (all == all) == all)) == (((all == all) == all) == (all == all) == all) == (((all == all) == all) == (all == all) == all);
-- p();
-- local b = (((aoa and aiai and adj and ahja and ajaj) or bby) and (cum or g or s or u) and aodod) == (((aoa and aiai and adj and ahja and ajaj) or bby) and (cum or g or s or u) and aodod)

